# Generated by Django 2.2.3 on 2019-08-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_onetooneroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetooneroom',
            name='limitation',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
